FROM node:lts-alpine

WORKDIR /var/www/frontend
COPY package.json /var/www/frontend

RUN npm uninstall -g @angular/cli
RUN npm cache verify
RUN npm install -g @angular/cli@latest
RUN npm install

EXPOSE 4200
CMD ["ng", "serve", "--host", "0.0.0.0"]