doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Security:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Security/Entity'
                prefix: 'App\Domain\Security\Entity'
                alias: Security
            Node:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Node/Entity'
                prefix: 'App\Domain\Node\Entity'
                alias: Node
            Course:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Course/Entity'
                prefix: 'App\Domain\Course\Entity'
                alias: Course
