doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            difficulty: App\Adventure\Doctrine\Type\DifficultyType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Security:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Security/Entity'
                prefix: 'App\Security\Entity'
                alias: Security
            Node:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Node/Entity'
                prefix: 'App\Node\Entity'
                alias: Node
            Adventure:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Adventure/Entity'
                prefix: 'App\Adventure\Entity'
                alias: Adventure
