security:
    enable_authenticator_manager: true
    password_hashers:
        App\Domain\Security\Entity\User:
            algorithm: auto
        App\Domain\Security\Entity\Administrator:
            algorithm: auto
    providers:
        users_doctrine:
            entity:
                class: App\Domain\Security\Entity\User
                property: email
        administrators_doctrine:
            entity:
                class: App\Domain\Security\Entity\Administrator
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            provider: administrators_doctrine
            form_login:
                login_path: admin_security_login
                check_path: admin_security_login
            logout:
                path: admin_security_logout
        main:
            pattern: ^/
            lazy: true
            provider: users_doctrine
            custom_authenticator: App\Infrastructure\Security\Guard\WebAuthenticator
            logout:
                path: security_logout
    access_control:
        - { path: ^/admin/security/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
