security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: bcrypt
    providers:
        user_provider:
            id: IncentiveFactory\IlEtaitUneFoisUnDev\Security\Provider\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: user_provider
            user_checker: IncentiveFactory\IlEtaitUneFoisUnDev\Security\UserChecker\UserChecker
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800
            logout:
                path: security_logout
                target: index
            custom_authenticators:
                - IncentiveFactory\IlEtaitUneFoisUnDev\Security\Guard\UserAuthenticator
    access_control:


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: bcrypt
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
