version: '3.7'
services:
  apache:
    container_name: apache
    build: build/apache
    ports:
      - "9000:80"
    volumes:
      - ./build/apache/vhosts:/etc/apache2/sites-enabled
      - .:/var/www/html
    restart: always
    networks:
      - dev
  mailer:
    image: schickling/mailcatcher
    container_name: mailer
    ports:
      - "9001:1080"
    networks:
      - dev
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "9002:5672"
      - "9003:15672"
    volumes:
      - queue-data:/var/lib/rabbitmq/
      - queue-log:/var/log/rabbitmq
    networks:
      - dev
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "9004:6379"
    networks:
      - dev
  database:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "9005:3306"
    networks:
      - dev
volumes:
  db-data:
  queue-data:
  queue-log:

networks:
  dev: