api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Security/Entity'
            - '%kernel.project_dir%/src/Adventure/Entity'
    formats:
        json:     ['application/json']
        jsonld:   ['application/ld+json']
        html:     ['text/html']
    exception_to_status:
        Symfony\Component\Messenger\Exception\ValidationFailedException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
