doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            difficulty: App\Adventure\Doctrine\Type\DifficultyType
            type: App\Adventure\Doctrine\Type\QuestTypeType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Security:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Security/Entity'
                prefix: 'App\Security\Entity'
                alias: Security
            Admin:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Admin/Entity'
                prefix: 'App\Admin\Entity'
                alias: Admin
            Content:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Content/Entity'
                prefix: 'App\Content\Entity'
                alias: Content
            Adventure:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Adventure/Entity'
                prefix: 'App\Adventure\Entity'
                alias: Adventure
