admin_controllers:
  resource: ../src/Admin/Controller/
  type: annotation

security_actions:
  resource: ../src/Security/Action/
  type: annotation
  prefix: /api/security
  name_prefix: security_

adventure_actions:
  resource: ../src/Adventure/Action/
  type: annotation
  prefix: /api/adventure
  name_prefix: adventure_

kernel:
  resource: ../src/Kernel.php
  type: annotation
