parameters:
    routing.ulid: '^[0-9A-Z]{26}$'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $projectDir: '%kernel.project_dir%'
            string $environment: '%kernel.environment%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/*/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Adventure\Controller\:
        resource: '../src/Adventure/Controller/'
        tags:
            - controller.service_arguments

    App\Security\OpenApi\UserDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: ['@.inner']
        decoration_priority: 3

    App\Adventure\OpenApi\QuestDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: ['@.inner']
        decoration_priority: 2

    App\Adventure\OpenApi\AdventureDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: ['@.inner']
        decoration_priority: 1

    App\Security\OpenApi\LoginDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: ['@.inner']
        decoration_priority: 0

    Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface: '@App\Security\Doctrine\Repository\UserRepository'