parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $projectDir: '%kernel.project_dir%'
            string $environment: '%kernel.environment%'

    _instanceof:
        App\Core\Bus\Command\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        App\Core\Bus\Query\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: query.bus }
        App\Core\Bus\Event\EventSubscriberInterface:
            tags:
                - { name: messenger.message_handler, bus: event.bus }
        App\Core\Http\Action\ActionInterface:
            tags:
                - controller.service_arguments

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Adventure\EntityListener\:
        resource: '../src/Adventure/EntityListener/'
        tags:
            - doctrine.orm.entity_listener
