parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $projectDir: '%kernel.project_dir%'
            string $environment: '%kernel.environment%'

    _instanceof:
        App\Core\CQRS\HandlerInterface:
            tags:
                - messenger.message_handler

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Adventure\EntityListener\:
        resource: '../src/Adventure/EntityListener/'
        tags:
            - doctrine.orm.entity_listener

    App\Security\Action\:
        resource: '../src/Security/Action/'
        tags:
            - controller.service_arguments
