security_controllers:
  resource: ../src/Security/Controller/
  type: annotation

admin_controllers:
  resource: ../src/Admin/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation
