parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $projectDir: '%kernel.project_dir%'
            string $environment: '%kernel.environment%'

    _instanceof:
        App\Domain\Shared\Command\HandlerInterface:
            tags:
                - messenger.message_handler

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
