parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $uploadsDir: '%uploads_directory%'

    _instanceof:
        IncentiveFactory\Domain\Shared\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        IncentiveFactory\Domain\Shared\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

        IncentiveFactory\Domain\Shared\Event\EventListener:
            tags:
                - { name: messenger.message_handler, bus: event.bus }

        IncentiveFactory\IlEtaitUneFoisUnDev\Doctrine\Type\AbstractEnumType:
            tags:
                - { name: 'app.doctrine_enum_type' }

    Symfony\Component\PasswordHasher\Hasher\NativePasswordHasher: ~

    Symfony\Component\PasswordHasher\PasswordHasherInterface: '@Symfony\Component\PasswordHasher\Hasher\NativePasswordHasher'

    IncentiveFactory\IlEtaitUneFoisUnDev\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Doctrine/Entity/'
            - '../src/Kernel.php'

    IncentiveFactory\Domain\:
        resource: '../vendor/incentive-factory/domain/src/'
