@startmindmap

*:Envie
    Je souhaite découvrir
    une nouvelle manière d'appréhender
    l'apprentissage de Symfony.;

**:Déjà inscrit
    Je suis déjà inscrit et je connais
    déjà le concept.;

***:Mon espace
    Quand je me connecte, je me
    rends automatiquement sur ma
    dernière sauvegarde et donc
    sur un écran spécifique.;

****:Nouvelle quête
    Quand j'arrive sur l'écran
    d'une nouvelle quête, je peux :
    - Lire la vidéo
    - Lire le texte;

*****:Finir une quête
    Je clique sur "Terminer"
    et on me propose plusieurs possibilités :
    - Des quêtes annexes
    - Suivre la quête principale
    - Changer de région;

**:Découverte
    J'arrive sur le site iletaitunefoisun.dev
    et je tombe sur la landing page
    qui m'explique le concept et comment
    commencer mon aventure pédagogique.;

***:Inscription
    Je m'inscris sur la plateforme en
    saisissant seulement mon adresse
    email et mon mot de passe.;

****:Première connexion
    Je me connecte pour la première fois
    et j'arrive sur la création de mon joueur.
    Je saisi le nom de mon personnage.;

*****:Didacticiel
    J'arrive sur le didacticiel qui m'explique
    dans un premier temps comment fonctionne
    l'ensemble de la plateforme, pour cela un enchaînement
    de modales que l'on peut passer.
    Nous arrivons donc sur la carte du monde;

******:Carte du monde
    Quand on arrive pour la première fois,
    on découvre la carte du monde avec
    les divers continents cliquables.
    Seul le continent "Didacticiel" est cliquable.;

@endmindmap
