name: Continuous Integration
on: [push]
jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Up needed docker
        run: make install
      - name: Initialize test environment
        run: make prepare env=test
      - name: Create key pair
        run: make generate-keypair env=test
      - name: Code quality
        run: make analyse
      - name: Run tests
        run: make tests
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./server/var/coverage/clover.xml
          flags: tests
