name: Continuous Integration
on: [push]
jobs:
  code-quality:
    runs-on: ubuntu-latest
    name: Code quality
    steps:
      - uses: actions/checkout@v2
      - name: Up needed docker
        run: docker-compose up -d apache
      - name: Install dependencies
        run: make composer-install
      - name: Code quality
        run: make analyse
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Up needed docker
        run: make install
      - name: Initialize test environment
        run: make prepare env=test
      - name: Create key pair
        run: make generate-keypair env=test
      - name: Run unit tests
        run: make tests
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./server/var/coverage/clover.xml
          flags: tests
